module(
    name = "rules_jooq_flyway_codegen",
    version = "0.8",
    compatibility_level = 1,
)

bazel_dep(name = "rules_java", version = "7.12.2")
bazel_dep(name = "rules_jvm_external", version = "6.7")

TESTCONTAINERS_VER = "1.21.4"

JOOQ_VER = "3.19.10"

FLYWAY_VER = "10.15.0"

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "rules_jooq_flyway_codegen_maven",
    artifacts = [
        "org.flywaydb:flyway-core:%s" % FLYWAY_VER,
        "org.flywaydb:flyway-database-postgresql:%s" % FLYWAY_VER,
        "org.flywaydb:flyway-mysql:%s" % FLYWAY_VER,
        "org.jooq:jooq:%s" % JOOQ_VER,
        "org.jooq:jooq-meta:%s" % JOOQ_VER,
        "org.jooq:jooq-codegen:%s" % JOOQ_VER,
        "org.testcontainers:testcontainers:%s" % TESTCONTAINERS_VER,
        "org.testcontainers:postgresql:%s" % TESTCONTAINERS_VER,
        "org.testcontainers:mariadb:%s" % TESTCONTAINERS_VER,
        "org.testcontainers:mysql:%s" % TESTCONTAINERS_VER,
        "org.postgresql:postgresql:42.2.14",
        "org.mariadb.jdbc:mariadb-java-client:2.6.2",
        "mysql:mysql-connector-java:8.0.21",
        "org.xerial:sqlite-jdbc:3.32.3.2",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "rules_jooq_flyway_codegen_maven")

maven_dev = use_extension(
    "@rules_jvm_external//:extensions.bzl",
    "maven",
    dev_dependency = True,
)
maven_dev.install(
    name = "rules_jooq_flyway_codegen_example_maven",
    artifacts = [
        "org.flywaydb:flyway-core:%s" % FLYWAY_VER,
        "org.flywaydb:flyway-database-postgresql:%s" % FLYWAY_VER,
        "org.flywaydb:flyway-mysql:%s" % FLYWAY_VER,
        "org.jooq:jooq:%s" % JOOQ_VER,
        "org.jooq:jooq-meta:%s" % JOOQ_VER,
        "org.jooq:jooq-codegen:%s" % JOOQ_VER,
        "org.testcontainers:testcontainers:%s" % TESTCONTAINERS_VER,
        "org.testcontainers:mysql:%s" % TESTCONTAINERS_VER,
        "mysql:mysql-connector-java:8.0.21",
        "com.zaxxer:HikariCP:3.4.5",
        "com.google.code.gson:gson:2.8.6",
        "com.sparkjava:spark-core:2.9.1",
        "org.slf4j:slf4j-simple:1.7.30",
        "org.xerial:sqlite-jdbc:3.32.3.2",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven_dev, "rules_jooq_flyway_codegen_example_maven")

google_java_format = use_extension(
    "//tools:extensions.bzl",
    "google_java_format",
    dev_dependency = True,
)
use_repo(google_java_format, "google_java_format")
